"""empty message

Revision ID: a0dddffac0f2
Revises: 
Create Date: 2020-04-01 16:06:30.593745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dddffac0f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('district', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_type', sa.Integer(), nullable=True),
    sa.Column('h_count', sa.Integer(), nullable=True),
    sa.Column('seats', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showname', sa.String(length=32), nullable=True),
    sa.Column('director', sa.String(length=16), nullable=True),
    sa.Column('leadingRole', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('openDay', sa.DateTime(), nullable=True),
    sa.Column('poster', sa.String(length=256), nullable=True),
    sa.Column('orderCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('u_email', sa.String(length=64), nullable=True),
    sa.Column('u_password', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('u_permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regionName', sa.String(length=16), nullable=True),
    sa.Column('cityCode', sa.Integer(), nullable=True),
    sa.Column('pinYin', sa.String(length=64), nullable=True),
    sa.Column('c_letter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_letter'], ['letter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_plan',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('mp_movie', sa.Integer(), nullable=True),
    sa.Column('mp_hall', sa.Integer(), nullable=True),
    sa.Column('mp_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mp_hall'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['mp_movie'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_user', sa.Integer(), nullable=True),
    sa.Column('o_movie_plan', sa.String(length=128), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['o_movie_plan'], ['movie_plan.id'], ),
    sa.ForeignKeyConstraint(['o_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_order', sa.Integer(), nullable=True),
    sa.Column('t_seat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['t_order'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('order')
    op.drop_table('movie_plan')
    op.drop_table('city')
    op.drop_table('user')
    op.drop_table('movies')
    op.drop_table('letter')
    op.drop_table('hall')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
